#!/bin/bash

echo "🧪 TESTE DO MÓDULO VENDAS"
echo "========================"
echo ""
echo "📋 Arquivos criados:"
echo "-------------------"
echo "model/Cliente.java"
echo "model/Venda.java"
echo "model/ItemVenda.java"
echo "repository/ClienteRepository.java"
echo "repository/VendaRepository.java"
echo "repository/ItemVendaRepository.java"
echo "service/VendaService.java"
echo "dto/VendaRequestDTO.java"
echo "dto/ItemVendaRequestDTO.java"
echo "dto/VendaResponseDTO.java"
echo "dto/ItemVendaResponseDTO.java"
echo "exception/EstoqueInsuficienteException.java"
echo "exception/GlobalExceptionHandler.java"
echo "controller/ClienteController.java"
echo "controller/VendaController.java"
echo ""
echo "🔧 Ações realizadas:"
echo "-------------------"
echo "1. Pastas service/, dto/, exception/ criadas"
echo "2. FornecedorController corrigido"
echo "3. Backup de Produto.java criado (Produto.java.backup)"
echo ""
echo "📌 PRÓXIMOS PASSOS:"
echo "1. Adicione manualmente em Produto.java:"
echo "   - Import: import java.util.HashSet; import java.util.Set;"
echo "   - Campo: @OneToMany(mappedBy = \"produto\", cascade = CascadeType.ALL)"
echo "            private Set<ItemVenda> itensVenda = new HashSet<>();"
echo ""
echo "2. Compile o projeto:"
echo "   mvn clean compile"
echo ""
echo "3. Execute a aplicação:"
echo "   mvn spring-boot:run"
echo ""
echo "4. Teste os endpoints:"
echo "   - POST /api/clientes"
echo "   - GET /api/produtos (para verificar estoque)"
echo "   - POST /api/vendas"
echo ""
echo "✅ Configuração concluída!"
